services:
  # Django 應用
  django-app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120"
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    ports:
      - "8002:8000"
    env_file:
      - .env.prod
    environment:
      - USE_SQLITE=true
      - PYTHONUNBUFFERED=1
    depends_on:
      - chromadb
    networks:
      - rag-network
    restart: unless-stopped

  # ChromaDB 向量資料庫
  chromadb:
    image: chromadb/chroma:0.4.24
    volumes:
      - ./chroma-data:/chroma/chroma
    expose:
      - "8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=False
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge
